---
# tasks file for /home/ansible/nginx/roles
- name: Install nginx
  yum: 
    name: "nginx"
  
- name: Start nginx
  service: 
    name: nginx
    state: started

- name: Check nginx status
  shell: | 
    systemctl enable nginx
    systemctl status nginx
  register: nginx_status
- debug: 
    var: nginx_status.stdout_lines

- name: Create index.html
  shell: |
    mkdir /home/nghipt7/web
    echo "index page" > /home/nghipt7/web/index.html

- name: Nginx-config
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"

- name: Webserver-config
  template:
    src: webserver.conf.j2
    dest: /etc/nginx/conf.d/webserver.conf
